# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import clsreg_pb2 as clsreg__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in clsreg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegressServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictPetalWidth = channel.unary_unary(
                '/iris.RegressService/PredictPetalWidth',
                request_serializer=clsreg__pb2.RegressRequest.SerializeToString,
                response_deserializer=clsreg__pb2.RegressRequest.FromString,
                _registered_method=True)


class RegressServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictPetalWidth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictPetalWidth': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPetalWidth,
                    request_deserializer=clsreg__pb2.RegressRequest.FromString,
                    response_serializer=clsreg__pb2.RegressRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iris.RegressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iris.RegressService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegressService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictPetalWidth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris.RegressService/PredictPetalWidth',
            clsreg__pb2.RegressRequest.SerializeToString,
            clsreg__pb2.RegressRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClassifyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictClass = channel.unary_unary(
                '/iris.ClassifyService/PredictClass',
                request_serializer=clsreg__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=clsreg__pb2.ClassifyRequest.FromString,
                _registered_method=True)


class ClassifyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictClass': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictClass,
                    request_deserializer=clsreg__pb2.ClassifyRequest.FromString,
                    response_serializer=clsreg__pb2.ClassifyRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iris.ClassifyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iris.ClassifyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClassifyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iris.ClassifyService/PredictClass',
            clsreg__pb2.ClassifyRequest.SerializeToString,
            clsreg__pb2.ClassifyRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
