# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clsreg.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'clsreg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lsreg.proto\x12\x04iris\"p\n\x0eRegressRequest\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x02\x12\x1d\n\x15predicted_petal_width\x18\x04 \x01(\x02\"\x80\x01\n\x0f\x43lassifyRequest\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x02\x12\x17\n\x0fpredicted_class\x18\x05 \x01(\t2Q\n\x0eRegressService\x12?\n\x11PredictPetalWidth\x12\x14.iris.RegressRequest\x1a\x14.iris.RegressRequest2O\n\x0f\x43lassifyService\x12<\n\x0cPredictClass\x12\x15.iris.ClassifyRequest\x1a\x15.iris.ClassifyRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clsreg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGRESSREQUEST']._serialized_start=22
  _globals['_REGRESSREQUEST']._serialized_end=134
  _globals['_CLASSIFYREQUEST']._serialized_start=137
  _globals['_CLASSIFYREQUEST']._serialized_end=265
  _globals['_REGRESSSERVICE']._serialized_start=267
  _globals['_REGRESSSERVICE']._serialized_end=348
  _globals['_CLASSIFYSERVICE']._serialized_start=350
  _globals['_CLASSIFYSERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
